# Generated by Django 4.2.6 on 2023-10-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='info',
            table='info',
        ),
    ]
